apiVersion: apps/v1
kind: Deployment
metadata:
  name: onify-agent-server
spec:
  selector:
    matchLabels:
      app: agent-server
  template:
    metadata:
      labels:
        app: agent-server
    spec:
     imagePullSecrets:
      - name: onify-regcred
     containers:
     - name: agent-server
       image: gcr.io/onify-containers/agent:master
       env:
         - name: log_level
           value: "2"
         - name: log_type
           value: "1"
         - name: hub_version
           value: "v2"
       ports:
       - name: agent-server
         containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: agent-server
spec:
  ports:
    - protocol: TCP
      name: agent-server
      port: 8080
  selector:
    app: agent-server
